NOTES:
  - "c,"
  - "d,"
  - "e,"
  - "f,"
  - "g,"
  - "a,"
  - "b,"
  - "c"
  - "d"
  - "e"
  - "f"
  - "g"
  - "a"
  - "b"
  - "c'"
  - "d'"
  - "e'"
  - "f'"
  - "g'"
  - "a'"
  - "b'"
  - "c''"
  - "d''"
  - "e''"
  - "f''"
  - "g''"
  - "a''"
  - "b''"

RYTHMS:
  - [4]
  - [8, 8, ]
  - [16, 16, 16, 16, ]
  - [8, 16, 16, ]
  - [16, 16, 8, ]

MAX_NOTES_PER_PAGE: 100

LILYPOND_HEADER: |
  #(set! paper-alist
  (cons '("my size" . (cons (* 21 cm) (* 2 cm))) paper-alist))

  \paper {
    #(set-paper-size "my size")
    print-page-number=false
  }
              
  \layout {
    indent = 0\cm
    \context {
      \Score
      \omit BarNumber
    }
  }
  { \fixed c'{\hide TimeSignature

LILYPOND_END: |
  }}

TRAIN_TO_OTHERS_RATIO: 0.33
VAL_TO_TEST_RATIO: 0.33
RANDOM_STATE: 42
